import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { LoginProvider } from "../Context/logincontext";
import { ThemeProvider } from "../Context/themecontext";
import { AdminProvider } from "../Context/admincontext";
import { ViewProvider } from "@/Context/ViewContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DairyWebApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full max-w-full overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-green-50 w-full max-w-full overflow-x-hidden`}
      > 
        <ThemeProvider>
        <LoginProvider>
        <AdminProvider>
        <ViewProvider>
              <div className="w-full max-w-full overflow-x-hidden">
                <Navbar />
                <div className="flex-1 flex flex-col w-full min-h-screen pt-16 md:pt-0">
                  {children}
                </div>
              </div>
        </ViewProvider>
        </AdminProvider>
        </LoginProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
